test

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,30 +1,29 @@
-#!/bin/bash
+#!/bin/sh
+#
+# An example hook script to verify what is about to be committed.
+# Called by "git commit" with no arguments. The hook should
+# exit with non-zero status after issuing an appropriate message if
+# it wants to stop the commit.
+#
+# To enable this hook, rename this file to "pre-commit".
 
-echo husky start
-hard_limit=$(git config hooks.filesizehardlimit)
-: ${hard_limit:=5000000}
+# Redirect output to stderr.
+exec 1>&2
 
-status=0
+CURRENT_DIR="$(pwd)"
+HAS_ERROR=""
 
-bytesToHuman() {
-  b=${1:-0}; d=''; s=0; S=({,K,M,G,T,P,E,Z,Y}B)
-  while ((b > 1000)); do
-    d="$(printf ".%01d" $((b % 1000 * 10 / 1000)))"
-    b=$((b / 1000))
-    let s++
-  done
-  echo "$b$d${S[$s]}"
-}
+for file in $(git diff --cached --name-only | sort | uniq); do
+	file_size=$(du -m $CURRENT_DIR/$file | awk '{print $1}')
+	if [ "$file_size" -ge 5 ]; then
+		echo "$file is over 5MB."
+		HAS_ERROR="1"
+	fi
+done
 
-# Iterate over the zero-delimited list of staged files.
-while IFS= read -r -d '' file ; do
-  hash=$(git ls-files -s "$file" | cut -d ' ' -f 2)
-  size=$(git cat-file -s "$hash")
+if [ "$HAS_ERROR" != "" ]; then
+    echo "Can't commit, fix errors first." >&2
+    exit 1
+fi
 
-  if (( $size > $hard_limit )); then
-    echo "Error: Cannot commit '$file' because it is $(bytesToHuman $size), which exceeds the hard size limit of $(bytesToHuman $hard_limit)."
-    status=1
-  fi
-done < <(git diff -z --staged --name-only --diff-filter=d)
-exit $statusundefined
-
+exit 0
